platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'SDWebImage', '~>3.7'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'GCJSONKit', '~> 1.5.0'
pod 'BeanTransitionManager', '~> 0.2.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SBJson', '~> 4.0.1'
pod 'GCJSONKit', '~> 1.5.0'
pod 'SVPullToRefresh'
pod 'IQKeyboardManager', '~> 3.2.4'
